modLoader="javafml"
loaderVersion="[40,)"
license="Apache license v2.0"

[[mods]]
modId="zenhorizon"
version="1.0_ALPHA"
displayName="Zen Horizon"
authors="WOSAJ"
description="hjskdfjahsjfh"

    [[dependencies.zenhorizon]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.zenhorizon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.zenhorizon]]
    modId="curios"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.zenhorizon]]
    modId="patchouli"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
